### PR TITLE
Updated MacOS compile notes.

### PR DESCRIPTION
**Pull request by fgheorghe**
Short update on how to compile on MacOS.

### CODE REVIEW

**Comment by ryobg** [comment]
Thank you! Nice surprise.

**Comment by fgheorghe** [comment]
No worries. Updated documentation in case someone would want to try it on MacOS.

I am struggling tho to convert OBJ files to height-maps, somehow the surfaces I'm getting are flat in WorldCreator2. 

Here is an example file, in case you would have a few minutes to kindly point me in the right direction:
[untitled.obj.zip](https://github.com/ryobg/obj2hmap/files/3706628/untitled.obj.zip)

The resulting map looks like this (ignore the colour, it's just the app I am using to view it), notice two bumps and that's it:
Screenshot 2019-10-09 at 10 41 34

The command I used:
./obj2hmap ~/Downloads/untitled.obj terrain.r16 4097 4097 4097 y u16 -1000 1000

Gave it some ridiculously large values just to try it, tried the documented params as well to no luck :-(

Thank you!

**Comment by ryobg** [comment]
Ok, let me see...

**Comment by fgheorghe** [comment]
Thank you - much appreciated!

**Comment by ryobg** [comment]
Aa... got it. Well, trouble is that I never made this tool enough sophisticated to work with any type of object files. In your case it turns out it lacks resolution. For example if you do:
```
./obj2hmap untitled.obj terrain.r16 32 65535 32 y u16
```
You will see your 32x32 map :) (a bit rotated though).

The tool works on vertex coordinates, not on triangle faces with projection and averaging. In my use case back then this was enough. If I had more free time I would enhance it, because batch conversion is better than running a dedicated GUI tool for such operations... Which reminds me that the screenshot up there, if it was from Zbrush, you can use Alpha's GrabDoc and get your terrain.

**Comment by fgheorghe** [comment]
Ah nice one, it works! I was using worldcreator 2 - a new terrain editor, but it seems to have obj imports broken, hence trying to convert obj to heightmaps. Will play a bit more with this later today, thank you again!

**Pull request merged**
